## LOCALHOST
### GET all patients
GET http://localhost:3000/patients

### GET patient by ID
GET http://localhost:3000/patients/679e801fa04d19f37756ea79

### CREATE new patient
POST http://localhost:3000/patients HTTP/1.1
Content-Type: application/json

{
    "name": "Charlie Brown",
    "dob": "12/22/85",
    "email": "charlie.brown@example.com",
    "address":{ 
      "street":"41 East Avenue",
      "city":"New York",
      "zip":"10003"
    },
  "phone":"242-333-5445",
    "insurer": "Aviva",
    "request": "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
}

### PUT patient
PUT http://localhost:3000/patients/67ad2156909f60da0b417ce6 HTTP/1.1
Content-Type: application/json 

{
    "name": "Charlie Brown",
    "dob": "12/22/85",
    "email": "charlie.brown@example.com",
    "address":{ 
      "street":"41 East Avenue",
      "city":"New York",
      "zip":"10003"
    },
  "phone":"242-333-9999",
    "insurer": "Aviva",
    "request": "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
}

### DELETE patient
DELETE http://localhost:3000/patients/67acf8d6e8700f93f480a20c HTTP/1.1
Content-Type: application/json
